fix: update driver source for kernel compatibility and improve deb packaging scripts
- Update driver source files for compatibility with newer kernel APIs
- Bump package version to 1.2.0
- Rewrite postinst: cleaner structure, add set -e, use -j4
- Rewrite prerm: proper module unload, cleanup firmware and source
- Add .gitignore to exclude .deb build artifacts

diff --git a/aic8800fdrvpackage/DEBIAN/postinst b/aic8800fdrvpackage/DEBIAN/postinst
--- a/aic8800fdrvpackage/DEBIAN/postinst
+++ b/aic8800fdrvpackage/DEBIAN/postinst
@@ -1,58 +1,55 @@
 #!/bin/bash
-Main_version=`uname -r |awk -F'.' '{print $1}'`
-Minor_version=`uname -r |awk -F'.' '{print $2}'`
-cp /AIC8800/aic.rules /etc/udev/rules.d
+set -e
+
+KVER=$(uname -r)
+SRC=/AIC8800
+
+echo "Installing AIC8800 WiFi driver for kernel ${KVER}..."
+
+# udev rules
+cp ${SRC}/aic.rules /etc/udev/rules.d/
 udevadm trigger
 udevadm control --reload
-echo "udev done"
+echo "udev rules installed."
+
+# eject virtual CD-ROM if present
 if [ -L /dev/aicudisk ]; then
-echo "device exist"
-eject /dev/aicudisk
-else
-echo "device not exist"
+    eject /dev/aicudisk
 fi
-cd /AIC8800/fw/
+
+# firmware
 rm -rf /lib/firmware/aic8800DC
-cp -rf /AIC8800/fw/aic8800DC /lib/firmware/
-echo "cp fw done"
-cd /AIC8800/drivers/aic8800/
-echo "Waiting 10 seconds for CPU cooling before compilation..."
-sleep 10
-nice -n 19 make
+cp -rf ${SRC}/fw/aic8800DC /lib/firmware/
+echo "Firmware installed."
+
+# compile driver
+cd ${SRC}/drivers/aic8800/
+make clean || true
+nice -n 19 make -j4
 if [ $? -ne 0 ]; then
-    echo "make failed, install aic8800 wifi drvier failed"
+    echo "ERROR: driver compilation failed"
     exit 1
 fi
 make install
 if [ $? -ne 0 ]; then
-    echo "make install failed, install aic8800 wifi driver failed"
+    echo "ERROR: driver installation failed"
     exit 1
 fi
-modprobe cfg80211
-insmod /AIC8800/drivers/aic8800/aic_load_fw/aic_load_fw.ko
-if [ $? -ne 0 ]; then
-    echo "insmode aic_load_fw failed, install aic8800 wifi driver failed"
-    exit 1
-fi
-insmod /AIC8800/drivers/aic8800/aic8800_fdrv/aic8800_fdrv.ko
-if [ $? -ne 0 ]; then
-    echo "insmod aic8800_fdrv failed, install aic8800 wifi drvier failed"
-    exit 1
-fi
-echo "insmod done"
-cd /AIC8800/aicrf_test/
-echo "Waiting 5 seconds for CPU cooling before test tools compilation..."
-sleep 5
+echo "Driver compiled and installed."
+
+# load modules
+modprobe cfg80211 2>/dev/null || true
+insmod ${SRC}/drivers/aic8800/aic_load_fw/aic_load_fw.ko
+insmod ${SRC}/drivers/aic8800/aic8800_fdrv/aic8800_fdrv.ko
+echo "Modules loaded."
+
+# compile test tools
+cd ${SRC}/aicrf_test/
+make clean || true
 nice -n 19 make
-if [ $? -ne 0 ]; then
-    echo "make failed, install aic8800 wifi driver failed"
-    exit 1
-fi
 make install
-if [ $? -ne 0 ]; then
-    echo "make install failed, install aic8800 wifi driver failed"
-    exit 1
-fi
+echo "Test tools installed."
+
 udevadm trigger
-echo "Install aic8800 wifi driver successful!!!!!"
+echo "AIC8800 WiFi driver installed successfully!"
 exit 0
